### ISSUE TITLE
Introduce E2E tests and CI integration

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-demos#15]
*   [ ] Prepare a set of tests that covers:
    *   Cloning the repository,
    *   Opening the demo directory,
    *   Installing dependencies,
    *   Running the server,
    *   Verifying if the demos work
*   [ ] Integrate tests with CI, so each PR would be tested

**Comment by mlewand** [comment]
At the very least it should check whether the editor is created and not crashed (as it could be a config issue).

And also a CRON that runs it at least once a day. Think of when CKE5 releases and there's duplicated module error or something like that.
