### ISSUE TITLE
Conflicting package versions

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-demos#29]
https://github.com/ckeditor/ckeditor5-demos/blob/c42a24ad566cfd1d7605df08f8e1e5749b585240/user-interface-classic/package.json#L117-L120

**Comment by Reinmar** [comment]
And why do we even have ckeditor5-collaboration in this demo?

**Comment by Reinmar** [comment]
Third thing: We don't need `resolutions` anymore. CKEditor 5 packages has all the dependencies locked to specific versions (as opposed to using caret ranges in the past).

**Comment by pszczesniak** [comment]
I've checked all issues mentioned above and i can confirm that they were fixed by [this PR](https://github.com/ckeditor/ckeditor5-demos/pull/27).
