### ISSUE TITLE
Error coming while integrating CKEditor 5 in my angular version 13

### ISSUE THREAD

**Issue by ruchamer** [ckeditor/ckeditor5-demos#32]
**ERROR:** TypeError: Cannot read properties of undefined (reading 'upload')

This above error is coming while i am integrating the CKEditor 5 in my angular version 13 project.
And I am integrating the image upload functionality, using this site as base : https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html

So, When i am clicking on image button and selecting the image and click on open button that time this error is coming.

<img width="467" alt="image" src="https://github.com/ckeditor/ckeditor5-demos/assets/156076720/3e71f025-c34f-43d1-9bed-24294d864e4b">
<img width="483" alt="Screenshot 2024-01-09 160306_1" src="https://github.com/ckeditor/ckeditor5-demos/assets/156076720/55f49bab-c84c-44aa-b4a7-6ad8f9b930ae">

**Comment by Witoso** [comment]
Hi! Thanks for the request. Please share with us your set up (build type, installation method) to help us debug.

**Comment by ruchamer** [comment]
Hi @Witoso we resolved the issue it is working now, Thank you for your concern.
