### ISSUE TITLE
Feature-rich editor

### ISSUE THREAD

**Issue by JTGiLard** [ckeditor/ckeditor5-demos#35]
Hi,

is there another way to download the feature-rich editor sample? When I opened the "index"  , it display "
Feature-rich editor
Discover the riches of our editor ✨
Read on to better understand the functionalities you can test with this demo....."

I can't seem to try the editor and Import from Word features.

Thanks.

**Comment by Witoso** [comment]
Hi! You need to run `npm install` and `npm start`, as the code needs the builds step.
